# This application shows how page rank algorythm can be used to create a rating of artists based on how they influenced
# other groups

from page_rank import PageRank

pr = PageRank()

# Starting from Selena Gomez

pr.addAll1('Selena Gomez', ["Britney Spears", "Beyoncé", "Christina Aguilera", "Rihanna", "Taylor Swift"])

pr.addAll1('Britney Spears', ['Madonna', 'Whitney Houston', 'Janet Jackson', 'Michael Jackson', 'Sheryl Crow'])
pr.addAll1('Beyoncé', ['Michael Jackson', 'Diana Ross', 'Tina Turner', 'Prince', 'Lauryn Hill'])
pr.addAll1('Christina Aguilera', ['Etta James', 'Whitney Houston', 'Mariah Carey', 'Janis Joplin', 'Madonna'])
pr.addAll1('Rihanna', ['Bob Marley', 'Beyoncé', 'Madonna', 'Mariah Carey', 'Janet Jackson'])
pr.addAll1('Taylor Swift', ['Shania Twain', 'Dixie Chicks', 'Faith Hill', 'Dolly Parton', 'James Taylor'])

pr.addAll1('Madonna', ['David Bowie', 'Debbie Harry', 'Karen Carpenter', 'Aretha Franklin', 'Prince'])
pr.addAll1('Whitney Houston', ['Aretha Franklin', 'Chaka Khan', 'Dionne Warwick', 'Gladys Knight', 'Roberta Flack'])
pr.addAll1('Janet Jackson', ['Michael Jackson', 'Prince', 'James Brown', 'Marvin Gaye', 'Tina Turner'])
pr.addAll1('Michael Jackson', ['James Brown', 'Diana Ross', 'Stevie Wonder', 'Fred Astaire', 'Sammy Davis Jr.'])
pr.addAll1('Sheryl Crow', ['Bob Dylan', 'The Beatles', 'The Rolling Stones', 'Elton John', 'Eagles'])
pr.addAll1('Diana Ross', ['Billie Holiday', 'Ella Fitzgerald', 'Etta James', 'Sam Cooke', 'Marvin Gaye'])
pr.addAll1('Tina Turner', ['Ray Charles', 'B.B. King', 'Little Richard', 'Elvis Presley', 'Mahalia Jackson'])
pr.addAll1('Prince', ['James Brown', 'Stevie Wonder', 'Sly and the Family Stone', 'Jimi Hendrix', 'Curtis Mayfield'])
pr.addAll1('Lauryn Hill', ['Bob Marley', 'Stevie Wonder', 'Nina Simone', 'Aretha Franklin', 'Marvin Gaye'])
pr.addAll1('Etta James', ['Billie Holiday', 'Dinah Washington', 'Bessie Smith', 'Louis Jordan', 'Mahalia Jackson'])
pr.addAll1('Mariah Carey', ['Aretha Franklin', 'Stevie Wonder', 'Gladys Knight', 'Al Green', 'Patti LaBelle'])
pr.addAll1('Janis Joplin', ['Bessie Smith', 'Odetta', 'Lead Belly', 'Big Mama Thornton', 'Etta James'])
pr.addAll1('Bob Marley', ['Ray Charles', 'Curtis Mayfield', 'Fats Domino', 'James Brown', 'The Impressions'])
pr.addAll1('Shania Twain', ['Dolly Parton', 'Patsy Cline', 'Willie Nelson', 'Waylon Jennings', 'The Eagles'])
pr.addAll1('Dixie Chicks', ['Emmylou Harris', 'Linda Ronstadt', 'Fleetwood Mac', 'Bonnie Raitt', 'Merle Haggard'])
pr.addAll1('Faith Hill', ['Reba McEntire', 'Aretha Franklin', 'Dolly Parton', 'Linda Ronstadt', 'Tina Turner'])
pr.addAll1('Dolly Parton', ['Patsy Cline', 'Kitty Wells', 'Hank Williams', 'Johnny Cash', 'The Carter Family'])
pr.addAll1('James Taylor', ['The Beatles', 'Carole King', 'Paul Simon', 'Buddy Holly', 'Ray Charles'])

pr.addAll1('David Bowie', ['Little Richard', 'Elvis Presley', 'The Beatles', 'Anthony Newley', 'The Velvet Underground'])
pr.addAll1('Debbie Harry', ['The Shangri-Las', 'David Bowie', 'Iggy Pop', 'The Velvet Underground', 'The Ramones'])
pr.addAll1('Karen Carpenter', ['Ella Fitzgerald', 'Frank Sinatra', 'The Beatles', 'Dionne Warwick', 'Burt Bacharach'])
pr.addAll1('Aretha Franklin', ['Clara Ward', 'Mahalia Jackson', 'Sam Cooke', 'Dinah Washington', 'Ray Charles'])
pr.addAll1('Chaka Khan', ['Aretha Franklin', 'Stevie Wonder', 'Joni Mitchell', 'Billie Holiday', 'Ella Fitzgerald'])
pr.addAll1('Dionne Warwick', ['Burt Bacharach', 'Sam Cooke', 'Dinah Washington', 'Sarah Vaughan', 'Aretha Franklin'])
pr.addAll1('Gladys Knight', ['Sam Cooke', 'Mahalia Jackson', 'B.B. King', 'Dinah Washington', 'Ray Charles'])
pr.addAll1('Roberta Flack', ['Nina Simone', 'Aretha Franklin', 'Sam Cooke', 'Sarah Vaughan', 'Donny Hathaway'])
pr.addAll1('James Brown', ['Louis Jordan', 'Ray Charles', 'Little Richard', 'Elvis Presley', 'Nat King Cole'])
pr.addAll1('Stevie Wonder', ['Ray Charles', 'Sam Cooke', 'Marvin Gaye', 'The Beatles', 'Bob Dylan'])
pr.addAll1('Sly and the Family Stone', ['James Brown', 'Ray Charles', 'Motown', 'Bob Dylan', 'The Beatles'])
pr.addAll1('Jimi Hendrix', ['Muddy Waters', 'B.B. King', 'Chuck Berry', 'Little Richard', 'Elvis Presley'])
pr.addAll1('Curtis Mayfield', ['The Impressions', 'Ray Charles', 'Sam Cooke', 'The Beatles', 'Marvin Gaye'])
pr.addAll1('Nina Simone', ['Billie Holiday', 'Mahalia Jackson', 'Bach', 'Mozart', 'Louis Armstrong'])
pr.addAll1('Billie Holiday', ['Louis Armstrong', 'Bessie Smith', 'Ethel Waters', 'Lester Young', 'Fats Waller'])
pr.addAll1('Dinah Washington', ['Bessie Smith', 'Louis Armstrong', 'Fats Waller', 'Billie Holiday', 'Mahalia Jackson'])
pr.addAll1('Bessie Smith', ['Ma Rainey', 'Mamie Smith', 'Clara Smith', 'Ethel Waters', 'Louis Armstrong'])
pr.addAll1('Louis Jordan', ['Duke Ellington', 'Cab Calloway', 'Louis Armstrong', 'Fats Waller', 'Count Basie'])
pr.addAll1('Mahalia Jackson', ['Bessie Smith', 'Blind Willie Johnson', 'Clara Ward', 'Dorsey Dixon', 'Gospel Pearls'])
pr.addAll1('Sam Cooke', ['Ray Charles', 'Nat King Cole', 'Louis Armstrong', 'Mahalia Jackson', 'Aretha Franklin'])
pr.addAll1('The Beatles', ['Chuck Berry', 'Elvis Presley', 'Buddy Holly', 'Little Richard', 'The Everly Brothers'])
pr.addAll1('The Rolling Stones', ['Chuck Berry', 'Muddy Waters', 'Elvis Presley', 'Little Richard', 'Buddy Holly'])
pr.addAll1('Elton John', ['Leon Russell', 'The Beatles', 'Ray Charles', 'Elvis Presley', 'Jerry Lee Lewis'])
pr.addAll1('Eagles', ['The Byrds', 'The Beach Boys', 'Jackson Browne', 'Buffalo Springfield', 'The Flying Burrito Brothers'])
pr.addAll1('Bob Dylan', ['Woody Guthrie', 'Robert Johnson', 'Lead Belly', 'Hank Williams', 'Little Richard'])
pr.addAll1('Fleetwood Mac', ['B.B. King', 'Elmore James', 'Robert Johnson', 'Chuck Berry', 'Howlin\' Wolf'])
pr.addAll1('Bonnie Raitt', ['Mississippi Fred McDowell', 'Muddy Waters', 'Sippie Wallace', 'Howlin\' Wolf', 'B.B. King'])
pr.addAll1('Merle Haggard', ['Bob Wills', 'Hank Williams', 'Lefty Frizzell', 'Jimmie Rodgers', 'Johnny Cash'])
pr.addAll1('Reba McEntire', ['Patsy Cline', 'Dolly Parton', 'Loretta Lynn', 'Tammy Wynette', 'Merle Haggard'])
pr.addAll1('Johnny Cash', ['Hank Williams', 'Jimmie Rodgers', 'The Carter Family', 'Bob Wills', 'Roy Acuff'])
pr.addAll1('The Carter Family', ['Jimmie Rodgers', 'Blind Willie McTell', 'A.P. Carter', 'Doc Watson', 'Maybelle Carter'])
pr.addAll1('Buddy Holly', ['Elvis Presley', 'Chuck Berry', 'Little Richard', 'Hank Williams', 'Bill Monroe'])
pr.addAll1('Ray Charles', ['Nat King Cole', 'Louis Jordan', 'Charles Brown', 'Art Tatum', 'Duke Ellington'])

pr.addAll1('Little Richard', ['Sister Rosetta Tharpe', 'Mahalia Jackson', 'Billy Wright', 'Roy Brown', 'B.B. King'])
pr.addAll1('Elvis Presley', ['Arthur Crudup', 'B.B. King', 'Roy Acuff', 'Dean Martin', 'Hank Snow'])
pr.addAll1('Anthony Newley', ['Frank Sinatra', 'Al Jolson', 'Ella Fitzgerald', 'George Gershwin', 'Judy Garland'])
pr.addAll1('The Velvet Underground', ['Bob Dylan', 'Bo Diddley', 'Howlin\' Wolf', 'The Rolling Stones', 'Chuck Berry'])
pr.addAll1('The Shangri-Las', ['The Ronettes', 'The Crystals', 'The Marvelettes', 'Diana Ross', 'The Shirelles'])
pr.addAll1('Iggy Pop', ['James Brown', 'The Doors', 'The Rolling Stones', 'The Velvet Underground', 'Elvis Presley'])
pr.addAll1('The Ramones', ['The Stooges', 'The Beach Boys', 'The Velvet Underground', 'The Beatles', 'Chuck Berry'])
pr.addAll1('Ella Fitzgerald', ['Louis Armstrong', 'Duke Ellington', 'Billie Holiday', 'Bing Crosby', 'Count Basie'])
pr.addAll1('Frank Sinatra', ['Bing Crosby', 'Billie Holiday', 'Louis Armstrong', 'Ella Fitzgerald', 'Judy Garland'])
pr.addAll1('Burt Bacharach', ['George Gershwin', 'Claude Debussy', 'Cole Porter', 'Maurice Ravel', 'Stravinsky'])
pr.addAll1('Clara Ward', ['Mahalia Jackson', 'Bessie Smith', 'Rosetta Tharpe', 'The Dixie Hummingbirds', 'Dinah Washington'])
pr.addAll1('James Brown', ['Ray Charles', 'Louis Jordan', 'Little Richard', 'Elvis Presley', 'Nat King Cole'])
pr.addAll1('Stevie Wonder', ['Ray Charles', 'Sam Cooke', 'Marvin Gaye', 'The Beatles', 'Bob Dylan'])
pr.addAll1('Bessie Smith', ['Ma Rainey', 'Mamie Smith', 'Clara Smith', 'Ethel Waters', 'Louis Armstrong'])
pr.addAll1('Louis Armstrong', ['King Oliver', 'Fletcher Henderson', 'Bessie Smith', 'Ma Rainey', 'Jelly Roll Morton'])
pr.addAll1('Chuck Berry', ['Nat King Cole', 'Louis Jordan', 'Muddy Waters', 'T-Bone Walker', 'Frank Sinatra'])
pr.addAll1('Buddy Holly', ['Elvis Presley', 'Chuck Berry', 'Little Richard', 'Hank Williams', 'Bill Monroe'])
pr.addAll1('Roy Acuff', ['Jimmie Rodgers', 'Uncle Dave Macon', 'The Carter Family', 'Blind Lemon Jefferson', 'Gene Autry'])

pr.addAll1('Sister Rosetta Tharpe', ['Blind Willie Johnson', 'Bessie Smith', 'Mahalia Jackson', 'Tampa Red', 'Fats Waller'])
pr.addAll1('Billy Wright', ['Roy Brown', 'Louis Jordan', 'Johnny Otis', 'Charles Brown', 'Big Joe Turner'])
pr.addAll1('Roy Brown', ['Louis Jordan', 'Cab Calloway', 'Fats Domino', 'Charles Brown', 'T-Bone Walker'])
pr.addAll1('B.B. King', ['T-Bone Walker', 'Blind Lemon Jefferson', 'Lonnie Johnson', 'Charlie Christian', 'Django Reinhardt'])
pr.addAll1('Arthur Crudup', ['Big Bill Broonzy', 'Tommy Johnson', 'Blind Lemon Jefferson', 'Son House', 'Lead Belly'])
pr.addAll1('Roy Acuff', ['Jimmie Rodgers', 'Uncle Dave Macon', 'The Carter Family', 'Blind Lemon Jefferson', 'Gene Autry'])
pr.addAll1('Dean Martin', ['Bing Crosby', 'Frank Sinatra', 'Louis Prima', 'Perry Como', 'The Mills Brothers'])
pr.addAll1('Hank Snow', ['Jimmie Rodgers', 'Vernon Dalhart', 'Hank Williams', 'Roy Acuff', 'Ernest Tubb'])
pr.addAll1('Chuck Berry', ['Nat King Cole', 'Louis Jordan', 'Muddy Waters', 'T-Bone Walker', 'Frank Sinatra'])
pr.addAll1('Carl Perkins', ['Elvis Presley', 'Muddy Waters', 'Blind Lemon Jefferson', 'Bill Monroe', 'Jimmie Rodgers'])
pr.addAll1('Frank Sinatra', ['Bing Crosby', 'Billie Holiday', 'Louis Armstrong', 'Ella Fitzgerald', 'Judy Garland'])
pr.addAll1('Bing Crosby', ['Al Jolson', 'Louis Armstrong', 'Enrico Caruso', 'Paul Whiteman', 'Bessie Smith'])
pr.addAll1('George Gershwin', ['Maurice Ravel', 'Igor Stravinsky', 'Claude Debussy', 'Scott Joplin', 'Ferde Grofé'])
pr.addAll1('Judy Garland', ['Al Jolson', 'Bing Crosby', 'Ethel Waters', 'Fred Astaire', 'Ella Fitzgerald'])
pr.addAll1('Bob Dylan', ['Woody Guthrie', 'Robert Johnson', 'Lead Belly', 'Hank Williams', 'Little Richard'])
pr.addAll1('Bo Diddley', ['John Lee Hooker', 'Louis Jordan', 'Muddy Waters', 'Chuck Berry', 'Big Joe Turner'])
pr.addAll1('Howlin\' Wolf', ['Charley Patton', 'Son House', 'Robert Johnson', 'Blind Lemon Jefferson', 'Muddy Waters'])
pr.addAll1('Ronettes', ['Darlene Love', 'Diana Ross', 'The Crystals', 'The Supremes', 'The Shirelles'])
pr.addAll1('The Crystals', ['The Ronettes', 'The Supremes', 'The Shirelles', 'Diana Ross', 'Martha and the Vandellas'])
pr.addAll1('The Doors', ['Chuck Berry', 'Elvis Presley', 'John Coltrane', 'Miles Davis', 'Bo Diddley'])
pr.addAll1('The Stooges', ['The Velvet Underground', 'The Doors', 'James Brown', 'Chuck Berry', 'The Rolling Stones'])
pr.addAll1('Billie Holiday', ['Louis Armstrong', 'Bessie Smith', 'Ethel Waters', 'Lester Young', 'Fats Waller'])
pr.addAll1('Louis Armstrong', ['King Oliver', 'Fletcher Henderson', 'Bessie Smith', 'Ma Rainey', 'Jelly Roll Morton'])
pr.addAll1('Count Basie', ['Fletcher Henderson', 'Duke Ellington', 'Benny Moten', 'Jelly Roll Morton', 'Louis Armstrong'])
pr.addAll1('Claude Debussy', ['Chopin', 'Wagner', 'J.S. Bach', 'Mussorgsky', 'Rameau'])
pr.addAll1('Cole Porter', ['Richard Rodgers', 'George Gershwin', 'Irving Berlin', 'Vincent Youmans', 'Jerome Kern'])
pr.addAll1('Maurice Ravel', ['Claude Debussy', 'Gabriel Fauré', 'Igor Stravinsky', 'Emmanuel Chabrier', 'Erik Satie'])
pr.addAll1('Stravinsky', ['Rimsky-Korsakov', 'Tchaikovsky', 'Debussy', 'Bach', 'Wagner'])
pr.addAll1('Duke Ellington', ['Jelly Roll Morton', 'James P. Johnson', 'Will Marion Cook', 'Fletcher Henderson', 'Louis Armstrong'])
pr.addAll1('King Oliver', ['Buddy Bolden', 'Freddie Keppard', 'Louis Armstrong', 'Kid Ory', 'Johnny Dodds'])


rating = pr.createRating()

print("Rating is: " + str(rating))

