# This application shows how page rank algorythm can be used to create a rating of artists based on how they influenced
# other groups

from page_rank import PageRank

pr = PageRank()

pr.addAll1('Metallica', ['Black Sabbath', 'Judas Priest', 'Motörhead', 'Diamond Head', 'Iron Maiden'])
pr.addAll1('Black Sabbath', ['Led Zeppelin', 'Cream', 'The Who', 'Jimi Hendrix', 'Deep Purple'])
pr.addAll1('Judas Priest', ['Black Sabbath', 'Led Zeppelin', 'Deep Purple', 'The Beatles', 'Alice Cooper'])
pr.addAll1('Motörhead', ['Chuck Berry', 'Little Richard', 'The Ramones', 'Jimi Hendrix', 'The Who'])
pr.addAll1('Diamond Head', ['Black Sabbath', 'Deep Purple', 'Led Zeppelin', 'Judas Priest', 'Iron Maiden'])
pr.addAll1('Iron Maiden', ['Black Sabbath', 'Led Zeppelin', 'Judas Priest', 'The Who', 'Deep Purple'])
pr.addAll1('Led Zeppelin', ['Muddy Waters', 'Robert Johnson', 'Howlin\' Wolf', 'The Beatles', 'Cream'])
pr.addAll1('Cream', ['Muddy Waters', 'Robert Johnson', 'Jimi Hendrix', 'The Beatles', 'Eric Clapton'])
pr.addAll1('The Who', ['Chuck Berry', 'Little Richard', 'The Kinks', 'The Beatles', 'Bob Dylan'])
pr.addAll1('Jimi Hendrix', ['Muddy Waters', 'Chuck Berry', 'Elvis Presley', 'B.B. King', 'Little Richard'])
pr.addAll1('Deep Purple', ['Cream', 'Led Zeppelin', 'Black Sabbath', 'The Beatles', 'Jimi Hendrix'])
pr.addAll1('Alice Cooper', ['The Beatles', 'The Rolling Stones', 'The Doors', 'The Who', 'David Bowie'])
pr.addAll1('The Ramones', ['The Stooges', 'The Velvet Underground', 'The Beach Boys', 'Chuck Berry', 'The Beatles'])
pr.addAll1('The Kinks', ['Chuck Berry', 'Buddy Holly', 'The Who', 'The Beatles', 'The Rolling Stones'])
pr.addAll1('David Bowie', ['Little Richard', 'Elvis Presley', 'Lou Reed', 'John Lennon', 'Syd Barrett'])
pr.addAll1('The Rolling Stones', ['Muddy Waters', 'Chuck Berry', 'James Brown', 'Bob Dylan', 'The Beatles'])
pr.addAll1('Nirvana', ['The Melvins', 'Black Flag', 'Sonic Youth', 'The Pixies', 'David Bowie'])
pr.addAll1('Radiohead', ['The Beatles', 'Pink Floyd', 'R.E.M.', 'Neil Young', 'The Smiths'])
pr.addAll1('Foo Fighters', ['Nirvana', 'The Pixies', 'Queen', 'David Bowie', 'The Who'])
pr.addAll1('Green Day', ['The Ramones', 'The Clash', 'Bad Religion', 'Rancid', 'The Beatles'])
pr.addAll1('Linkin Park', ['Nine Inch Nails', 'Depeche Mode', 'Metallica', 'Alice in Chains', 'Korn'])
pr.addAll1('Guns N\' Roses', ['Led Zeppelin', 'Aerosmith', 'The Rolling Stones', 'Queen', 'David Bowie'])
pr.addAll1('Blink-182', ['The Ramones', 'Green Day', 'Weezer', 'Bad Religion', 'Sum 41'])
pr.addAll1('Red Hot Chili Peppers', ['Funkadelic', 'Sly and the Family Stone', 'Prince', 'James Brown', 'The Jimi Hendrix Experience'])
pr.addAll1('Pearl Jam', ['The Who', 'The Beatles', 'Neil Young', 'The Rolling Stones', 'Pink Floyd'])
pr.addAll1('Alice in Chains', ['Black Sabbath', 'Kiss', 'Led Zeppelin', 'Stone Temple Pilots', 'Pantera'])
pr.addAll1('System of a Down', ['Metallica', 'Korn', 'Faith No More', 'Pantera', 'Slipknot'])
pr.addAll1('Avenged Sevenfold', ['Metallica', 'Iron Maiden', 'Megadeth', 'Pantera', 'Guns N\' Roses'])
pr.addAll1('Slipknot', ['Korn', 'Sepultura', 'System of a Down', 'Metallica', 'Alice in Chains'])
pr.addAll1('Disturbed', ['Metallica', 'Pantera', 'Korn', 'System of a Down', 'Alice in Chains'])
pr.addAll1('Nine Inch Nails', ['Marilyn Manson', 'Kraftwerk', 'David Bowie', 'The Cure', 'Depeche Mode'])
pr.addAll1('Tool', ['King Crimson', 'Pink Floyd', 'The Beatles', 'Rush', 'A Perfect Circle'])
pr.addAll1('My Chemical Romance', ['The Cure', 'The Misfits', 'Fall Out Boy', 'Panic! At The Disco', 'Green Day'])
pr.addAll1('Panic! At The Disco', ['Fall Out Boy', 'My Chemical Romance', 'The Smiths', 'Queen', 'David Bowie'])
pr.addAll1('Paramore', ['No Doubt', 'Jimmy Eat World', 'Fall Out Boy', 'The Starting Line', 'The Cure'])
pr.addAll1('Twenty One Pilots', ['Mumford & Sons', 'Panic! At The Disco', 'Fall Out Boy', 'The Postal Service', 'Radiohead'])
pr.addAll1('Imagine Dragons', ['OneRepublic', 'Mumford & Sons', 'The Lumineers', 'Coldplay', 'Kings of Leon'])
pr.addAll1('The Killers', ['David Bowie', 'U2', 'Bruce Springsteen', 'The Cure', 'Joy Division'])
pr.addAll1('The 1975', ['The Cure', 'The Smiths', 'Joy Division', 'Radiohead', 'The Killers'])
pr.addAll1('Hozier', ['Bob Dylan', 'Jeff Buckley', 'Radiohead', 'Fleet Foxes', 'Nick Drake'])
pr.addAll1('Shawn Mendes', ['Justin Bieber', 'Ed Sheeran', 'One Direction', 'Taylor Swift', 'The Script'])
pr.addAll1('Ed Sheeran', ['Damien Rice', 'Bob Dylan', 'Taylor Swift', 'Justin Bieber', 'Beyoncé'])
pr.addAll1('Taylor Swift', ['Shania Twain', 'The Dixie Chicks', 'Katy Perry', 'Madonna', 'Beyoncé'])
pr.addAll1('Katy Perry', ['Madonna', 'Britney Spears', 'Lady Gaga', 'Taylor Swift', 'Christina Aguilera'])
pr.addAll1('Beyoncé', ['Destiny\'s Child', 'Tina Turner', 'Janet Jackson', 'Madonna', 'Alicia Keys'])
pr.addAll1('Lady Gaga', ['Madonna', 'David Bowie', 'Elton John', 'Michael Jackson', 'Kylie Minogue'])
pr.addAll1('Bruno Mars', ['Michael Jackson', 'Prince', 'James Brown', 'Marvin Gaye', 'The Beatles'])
pr.addAll1('Rihanna', ['Madonna', 'Beyoncé', 'Michael Jackson', 'Lady Gaga', 'Tina Turner'])
pr.addAll1('Justin Bieber', ['Usher', 'Chris Brown', 'Rihanna', 'Michael Jackson', 'Akon'])
pr.addAll1('Billie Eilish', ['Lana Del Rey', 'Kurt Cobain', 'Radiohead', 'The Beatles', 'Tyler, the Creator'])
pr.addAll1('Dua Lipa', ['Madonna', 'Lady Gaga', 'Rihanna', 'Katy Perry', 'Britney Spears'])
pr.addAll1('Ariana Grande', ['Mariah Carey', 'Whitney Houston', 'Beyoncé', 'Rihanna', 'Christina Aguilera'])
pr.addAll1('Sam Smith', ['Amy Winehouse', 'Adele', 'Sade', 'Whitney Houston', 'George Michael'])
pr.addAll1('Lana Del Rey', ['Nancy Sinatra', 'Bob Dylan', 'The Beatles', 'Kurt Cobain', 'David Bowie'])
pr.addAll1('Post Malone', ['Kanye West', 'Drake', 'Juice WRLD', 'Travis Scott', 'Ozzy Osbourne'])
pr.addAll1('Travis Scott', ['Kanye West', 'Kid Cudi', 'Lil Wayne', 'Drake', 'OutKast'])
pr.addAll1('Lil Nas X', ['Billy Ray Cyrus', 'Nas', 'Kacey Musgraves', 'Travis Scott', 'Dolly Parton'])
pr.addAll1('Sza', ['Aaliyah', 'Erykah Badu', 'Beyoncé', 'Frank Ocean', 'Rihanna'])
pr.addAll1('Megan Thee Stallion', ['Nicki Minaj', 'Cardi B', 'Lil’ Kim', 'Trina', 'Missy Elliott'])
pr.addAll1('Cardi B', ['Nicki Minaj', 'Lil’ Kim', 'Remy Ma', 'Megan Thee Stallion', 'Missy Elliott'])
pr.addAll1('Doja Cat', ['Nicki Minaj', 'Megan Thee Stallion', 'Rihanna', 'Beyoncé', 'SZA'])
pr.addAll1('BTS', ['Big Bang', 'EXO', 'SEVENTEEN', 'TXT', 'Got7'])
pr.addAll1('Blackpink', ['2NE1', 'Girls\' Generation', 'Wonder Girls', 'f(x)', 'Red Velvet'])
pr.addAll1('Bad Bunny', ['J Balvin', 'Daddy Yankee', 'Ozuna', 'Maluma', 'Karol G'])
pr.addAll1('J Balvin', ['Daddy Yankee', 'Ozuna', 'Karol G', 'Nicky Jam', 'Bad Bunny'])
pr.addAll1('Karol G', ['Shakira', 'J Balvin', 'Nicky Jam', 'Ozuna', 'Maluma'])
pr.addAll1('Nicky Jam', ['Daddy Yankee', 'J Balvin', 'Ozuna', 'Karol G', 'Maluma'])
pr.addAll1('Shakira', ['Carlos Vives', 'Juanes', 'Ricky Martin', 'Marc Anthony', 'Maluma'])
pr.addAll1('Ricky Martin', ['Julio Iglesias', 'Marc Anthony', 'Shakira', 'Enrique Iglesias', 'J Balvin'])
pr.addAll1('Enrique Iglesias', ['Julio Iglesias', 'Ricky Martin', 'Marc Anthony', 'Shakira', 'Pitbull'])
pr.addAll1('Pitbull', ['Lil Jon', 'DJ Khaled', 'Enrique Iglesias', 'Ricky Martin', 'J Balvin'])

rating = pr.createRating()

print("Rating is: " + str(rating))

