# This application shows how page rank algorythm can be used to create a rating of artists based on how they influenced
# other groups

from page_rank import PageRank

pr = PageRank()

pr.addAll1('Dream Theater', ['Rush', 'Queensrÿche', 'Tool', 'Symphony X', 'Fates Warning'])
pr.addAll1('Rush', ['Yes', 'Genesis', 'King Crimson', 'Pink Floyd', 'The Beatles'])
pr.addAll1('Queensrÿche', ['Metallica', 'Iron Maiden', 'Dream Theater', 'Fates Warning', 'Judas Priest'])
pr.addAll1('Tool', ['A Perfect Circle', 'Mastodon', 'Meshuggah', 'Opeth', 'King Crimson'])
pr.addAll1('Symphony X', ['Dream Theater', 'Fates Warning', 'Nevermore', 'Ayreon', 'Blind Guardian'])
pr.addAll1('Fates Warning', ['Dream Theater', 'Queensrÿche', 'Crimson Glory', 'Shadow Gallery', 'Symphony X'])
pr.addAll1('Yes', ['Genesis', 'Rush', 'Jethro Tull', 'Emerson, Lake & Palmer', 'Pink Floyd'])
pr.addAll1('Genesis', ['Peter Gabriel', 'Phil Collins', 'Yes', 'King Crimson', 'Jethro Tull'])
pr.addAll1('King Crimson', ['Robert Fripp', 'Brian Eno', 'Gong', 'Yes', 'Tool'])
pr.addAll1('Pink Floyd', ['David Gilmour', 'Roger Waters', 'The Beatles', 'Yes', 'Genesis'])
pr.addAll1('Metallica', ['Black Sabbath', 'Megadeth', 'Pantera', 'Iron Maiden', 'Judas Priest'])
pr.addAll1('Iron Maiden', ['Black Sabbath', 'Judas Priest', 'Metallica', 'Motörhead', 'Alice Cooper'])
pr.addAll1('Megadeth', ['Metallica', 'Slayer', 'Anthrax', 'Pantera', 'Judas Priest'])
pr.addAll1('Pantera', ['Metallica', 'Slayer', 'Sepultura', 'Korn', 'Lamb of God'])
pr.addAll1('Judas Priest', ['Black Sabbath', 'Iron Maiden', 'Ozzy Osbourne', 'Metallica', 'Motörhead'])
pr.addAll1('A Perfect Circle', ['Tool', 'Puscifer', 'Nine Inch Nails', 'Depeche Mode', 'The Smashing Pumpkins'])
pr.addAll1('Mastodon', ['Metallica', 'Neurosis', 'The Dillinger Escape Plan', 'Converge', 'Opeth'])
pr.addAll1('Meshuggah', ['Fear Factory', 'Gojira', 'The Dillinger Escape Plan', 'Periphery', 'Animals as Leaders'])
pr.addAll1('Opeth', ['Porcupine Tree', 'Anathema', 'Death', 'Tool', 'In Flames'])
pr.addAll1('Blind Guardian', ['Helloween', 'Gamma Ray', 'Nightwish', 'Rhapsody of Fire', 'Sonata Arctica'])
pr.addAll1('Nevermore', ['Sanctuary', 'Queensrÿche', 'Demon Hunter', 'Soilwork', 'Symphony X'])
pr.addAll1('Ayreon', ['Transatlantic', 'The Flower Kings', 'Dream Theater', 'Symphony X', 'Haken'])
pr.addAll1('Crimson Glory', ['Queensrÿche', 'Fates Warning', 'Dream Theater', 'Iron Maiden', 'Metallica'])
pr.addAll1('Shadow Gallery', ['Fates Warning', 'Symphony X', 'Dream Theater', 'Queensrÿche', 'Ayreon'])
pr.addAll1('Jethro Tull', ['Yes', 'Genesis', 'King Crimson', 'Camel', 'Emerson, Lake & Palmer'])
pr.addAll1('Emerson, Lake & Palmer', ['Yes', 'King Crimson', 'Jethro Tull', 'Pink Floyd', 'Rush'])
pr.addAll1('The Beatles', ['The Rolling Stones', 'Bob Dylan', 'The Beach Boys', 'Led Zeppelin', 'The Who'])
pr.addAll1('The Rolling Stones', ['The Beatles', 'Chuck Berry', 'Muddy Waters', 'Bob Dylan', 'Elvis Presley'])
pr.addAll1('Bob Dylan', ['Woody Guthrie', 'Johnny Cash', 'Neil Young', 'Joni Mitchell', 'Simon & Garfunkel'])
pr.addAll1('The Beach Boys', ['The Beatles', 'Jan & Dean', 'The Four Seasons', 'Buffalo Springfield', 'Simon & Garfunkel'])
pr.addAll1('Led Zeppelin', ['The Beatles', 'The Rolling Stones', 'Cream', 'The Who', 'Jimi Hendrix'])
pr.addAll1('The Who', ['The Beatles', 'The Rolling Stones', 'Jimi Hendrix', 'Cream', 'The Kinks'])
pr.addAll1('Cream', ['The Beatles', 'The Rolling Stones', 'Jimi Hendrix', 'Eric Clapton', 'Jeff Beck'])
pr.addAll1('Jimi Hendrix', ['B.B. King', 'Chuck Berry', 'Little Richard', 'Elvis Presley', 'The Beatles'])
pr.addAll1('B.B. King', ['Muddy Waters', 'John Lee Hooker', 'Albert King', 'Howlin\' Wolf', 'Freddie King'])
pr.addAll1('Chuck Berry', ['Little Richard', 'Elvis Presley', 'Fats Domino', 'Buddy Holly', 'Jerry Lee Lewis'])
pr.addAll1('Little Richard', ['Chuck Berry', 'Fats Domino', 'Ray Charles', 'Sam Cooke', 'Elvis Presley'])
pr.addAll1('Fats Domino', ['Little Richard', 'Chuck Berry', 'Jerry Lee Lewis', 'Ray Charles', 'Buddy Holly'])
pr.addAll1('Buddy Holly', ['Elvis Presley', 'Little Richard', 'Chuck Berry', 'Ritchie Valens', 'The Big Bopper'])
pr.addAll1('Jerry Lee Lewis', ['Elvis Presley', 'Little Richard', 'Fats Domino', 'Chuck Berry', 'Buddy Holly'])

# Continuing to expand with additional artists
pr.addAll1('Alice Cooper', ['David Bowie', 'Black Sabbath', 'Kiss', 'Mötley Crüe', 'Twisted Sister'])
pr.addAll1('Kiss', ['Alice Cooper', 'The Beatles', 'Queen', 'David Bowie', 'Led Zeppelin'])
pr.addAll1('Mötley Crüe', ['Kiss', 'Alice Cooper', 'Twisted Sister', 'Guns N\' Roses', 'Poison'])
pr.addAll1('Twisted Sister', ['Alice Cooper', 'Kiss', 'Mötley Crüe', 'Quiet Riot', 'Dokken'])
pr.addAll1('Guns N\' Roses', ['Led Zeppelin', 'Aerosmith', 'The Rolling Stones', 'Queen', 'David Bowie'])
pr.addAll1('Aerosmith', ['The Rolling Stones', 'The Beatles', 'Jimi Hendrix', 'Led Zeppelin', 'Queen'])
pr.addAll1('Queens of the Stone Age', ['Kyuss', 'Screaming Trees', 'Foo Fighters', 'Soundgarden', 'Alice in Chains'])
pr.addAll1('Foo Fighters', ['Nirvana', 'Sunny Day Real Estate', 'The Smashing Pumpkins', 'Queens of the Stone Age', 'Weezer'])
pr.addAll1('Soundgarden', ['Alice in Chains', 'Nirvana', 'Pearl Jam', 'Temple of the Dog', 'Stone Temple Pilots'])
pr.addAll1('Nirvana', ['The Melvins', 'Punk Rock', 'Sonic Youth', 'Pixies', 'Alice in Chains'])
pr.addAll1('Pearl Jam', ['Soundgarden', 'Alice in Chains', 'Stone Temple Pilots', 'Nirvana', 'Temple of the Dog'])
pr.addAll1('Stone Temple Pilots', ['Pearl Jam', 'Soundgarden', 'Alice in Chains', 'Nirvana', 'Jane’s Addiction'])
pr.addAll1('Alice in Chains', ['Soundgarden', 'Pearl Jam', 'Nirvana', 'Temple of the Dog', 'Stone Temple Pilots'])
pr.addAll1('My Chemical Romance', ['The Used', 'Fall Out Boy', 'Panic! At The Disco', 'Taking Back Sunday', 'Green Day'])
pr.addAll1('Fall Out Boy', ['My Chemical Romance', 'Panic! At The Disco', 'Paramore', 'All-American Rejects', 'Simple Plan'])
pr.addAll1('Panic! At The Disco', ['Fall Out Boy', 'My Chemical Romance', 'The Used', 'Paramore', 'Blink-182'])
pr.addAll1('Paramore', ['No Doubt', 'Jimmy Eat World', 'Fall Out Boy', 'The Starting Line', 'The All-American Rejects'])
pr.addAll1('Hozier', ['Jeff Buckley', 'Radiohead', 'Bob Dylan', 'Fleet Foxes', 'Nick Drake'])
pr.addAll1('Shawn Mendes', ['Justin Bieber', 'Ed Sheeran', 'One Direction', 'Taylor Swift', 'The Script'])
pr.addAll1('Ed Sheeran', ['Damien Rice', 'Bob Dylan', 'Taylor Swift', 'Justin Bieber', 'Beyoncé'])
pr.addAll1('Taylor Swift', ['Shania Twain', 'The Dixie Chicks', 'Katy Perry', 'Madonna', 'Beyoncé'])
pr.addAll1('Katy Perry', ['Madonna', 'Britney Spears', 'Lady Gaga', 'Taylor Swift', 'Christina Aguilera'])
pr.addAll1('Britney Spears', ['Madonna', 'Janet Jackson', 'Christina Aguilera', 'NSYNC', 'Backstreet Boys'])
pr.addAll1('Christina Aguilera', ['Mariah Carey', 'Whitney Houston', 'Britney Spears', 'Beyoncé', 'Pink'])
pr.addAll1('Beyoncé', ['Destiny\'s Child', 'Alicia Keys', 'Janet Jackson', 'Rihanna', 'Lady Gaga'])
pr.addAll1('Rihanna', ['Beyoncé', 'Lady Gaga', 'Katy Perry', 'Nicki Minaj', 'Alicia Keys'])
pr.addAll1('Nicki Minaj', ['Lil Wayne', 'Missy Elliott', 'Cardi B', 'Ariana Grande', 'Rihanna'])
pr.addAll1('Cardi B', ['Nicki Minaj', 'Megan Thee Stallion', 'Lil Kim', 'Missy Elliott', 'Rihanna'])
pr.addAll1('Megan Thee Stallion', ['Nicki Minaj', 'Cardi B', 'Lil Kim', 'Missy Elliott', 'Beyoncé'])
pr.addAll1('Ariana Grande', ['Mariah Carey', 'Beyoncé', 'Whitney Houston', 'Britney Spears', 'Lady Gaga'])
pr.addAll1('Kacey Musgraves', ['Patsy Cline', 'Dolly Parton', 'Loretta Lynn', 'Shania Twain', 'Miranda Lambert'])
pr.addAll1('Miranda Lambert', ['Shania Twain', 'The Chicks', 'Carrie Underwood', 'Kacey Musgraves', 'Reba McEntire'])
pr.addAll1('Carrie Underwood', ['Faith Hill', 'Shania Twain', 'Reba McEntire', 'Miranda Lambert', 'Kacey Musgraves'])
pr.addAll1('Dolly Parton', ['Patsy Cline', 'Loretta Lynn', 'Emmylou Harris', 'Tammy Wynette', 'Johnny Cash'])
pr.addAll1('Lorde', ['Ella Yelich-O’Connor', 'Florence Welch', 'Taylor Swift', 'Halsey', 'Billie Eilish'])
pr.addAll1('Billie Eilish', ['Lorde', 'Tame Impala', 'The Neighbourhood', 'Tyler, The Creator', 'Khalid'])
pr.addAll1('Halsey', ['Lorde', 'Taylor Swift', 'Katy Perry', 'Billie Eilish', 'Panic! At The Disco'])
pr.addAll1('Lana Del Rey', ['Nina Simone', 'Joni Mitchell', 'Cat Power', 'Amy Winehouse', 'Florence Welch'])
pr.addAll1('The 1975', ['The Cure', 'The Smiths', 'The Killers', 'Oasis', 'Radiohead'])
pr.addAll1('The Killers', ['Bruce Springsteen', 'U2', 'Oasis', 'David Bowie', 'Duran Duran'])
pr.addAll1('The Cure', ['Joy Division', 'Siouxsie and the Banshees', 'The Smiths', 'New Order', 'Echo & The Bunnymen'])
pr.addAll1('Joy Division', ['The Cure', 'Bauhaus', 'The Smiths', 'Echo & The Bunnymen', 'Siouxsie and the Banshees'])
pr.addAll1('The Smiths', ['Joy Division', 'The Cure', 'Echo & The Bunnymen', 'Siouxsie and the Banshees', 'Pulp'])
pr.addAll1('Pulp', ['The Smiths', 'Suede', 'Blur', 'Radiohead', 'Oasis'])
pr.addAll1('Blur', ['Oasis', 'Pulp', 'The Verve', 'Radiohead', 'The Cure'])
pr.addAll1('Oasis', ['The Beatles', 'The Rolling Stones', 'The Smiths', 'Blur', 'T-Rex'])
pr.addAll1('The Verve', ['Oasis', 'Radiohead', 'Blur', 'Pulp', 'The Cure'])
pr.addAll1('Radiohead', ['The Bends', 'Pink Floyd', 'Talking Heads', 'Nirvana', 'The Smiths'])
pr.addAll1('Arctic Monkeys', ['The Strokes', 'The White Stripes', 'Oasis', 'Blur', 'Radiohead'])
pr.addAll1('The Strokes', ['Oasis', 'The White Stripes', 'The Libertines', 'Arctic Monkeys', 'Interpol'])
pr.addAll1('The Libertines', ['Oasis', 'The Strokes', 'Blur', 'Pulp', 'Radiohead'])
pr.addAll1('Interpol', ['Joy Division', 'The Cure', 'The Strokes', 'Franz Ferdinand', 'The National'])
pr.addAll1('Franz Ferdinand', ['The Strokes', 'Bloc Party', 'Arctic Monkeys', 'Radiohead', 'Interpol'])
pr.addAll1('The National', ['Interpol', 'Bon Iver', 'The War on Drugs', 'Fleet Foxes', 'Vampire Weekend'])
pr.addAll1('Vampire Weekend', ['The National', 'Grizzly Bear', 'Phoenix', 'Fleet Foxes', 'Beach House'])
pr.addAll1('Grizzly Bear', ['Fleet Foxes', 'Animal Collective', 'The National', 'Bon Iver', 'Sufjan Stevens'])
pr.addAll1('Bon Iver', ['Sufjan Stevens', 'The National', 'Fleet Foxes', 'James Blake', 'Iron & Wine'])
pr.addAll1('James Blake', ['Bon Iver', 'Brian Eno', 'Frank Ocean', 'FKA Twigs', 'Sampha'])
pr.addAll1('FKA Twigs', ['Björk', 'James Blake', 'Beyoncé', 'Arca', 'Sufjan Stevens'])
pr.addAll1('Frank Ocean', ['Tyler, The Creator', 'Beyoncé', 'Kendrick Lamar', 'Sufjan Stevens', 'FKA Twigs'])
pr.addAll1('Kendrick Lamar', ['Dr. Dre', 'Snoop Dogg', 'Nas', 'JAY-Z', 'Tupac Shakur'])
pr.addAll1('JAY-Z', ['Notorious B.I.G.', 'Nas', 'Kanye West', 'Dr. Dre', 'Lil Wayne'])
pr.addAll1('Dr. Dre', ['Snoop Dogg', 'Eminem', 'Kendrick Lamar', '50 Cent', 'N.W.A.'])
pr.addAll1('Eminem', ['Dr. Dre', 'Notorious B.I.G.', '2Pac', 'Jay-Z', '50 Cent'])
pr.addAll1('50 Cent', ['Eminem', 'Dr. Dre', 'Snoop Dogg', 'Kanye West', 'Lil Wayne'])
pr.addAll1('Lil Wayne', ['Juvenile', 'Birdman', 'Drake', 'Nicki Minaj', 'Kendrick Lamar'])
pr.addAll1('Drake', ['Lil Wayne', 'Kanye West', 'JAY-Z', 'Future', 'Travis Scott'])
pr.addAll1('Travis Scott', ['Drake', 'Kanye West', 'Kid Cudi', 'Lil Uzi Vert', 'Juice WRLD'])
pr.addAll1('Kid Cudi', ['Kanye West', 'Travis Scott', 'Drake', 'Jaden Smith', 'Lil Wayne'])
pr.addAll1('Post Malone', ['Kanye West', 'Drake', 'Travis Scott', '21 Savage', 'Lil Uzi Vert'])
pr.addAll1('21 Savage', ['Metro Boomin', 'Post Malone', 'Lil Uzi Vert', 'Drake', 'Future'])
pr.addAll1('SZA', ['Frank Ocean', 'Beyoncé', 'Solange', 'Janelle Monáe', 'Kendrick Lamar'])
pr.addAll1('Solange', ['Beyoncé', 'Frank Ocean', 'Erykah Badu', 'Janelle Monáe', 'Ari Lennox'])
pr.addAll1('Janelle Monáe', ['Prince', 'Erykah Badu', 'Solange', 'Frank Ocean', 'Anderson .Paak'])
pr.addAll1('Anderson .Paak', ['Dr. Dre', 'Kendrick Lamar', 'Dilla', 'Thundercat', 'Snoop Dogg'])
pr.addAll1('Thundercat', ['Flying Lotus', 'Kamasi Washington', 'Anderson .Paak', 'Erykah Badu', 'Robert Glasper'])


rating = pr.createRating()

print("Rating is: " + str(rating))

